[package]
name = "tantivy"
version = "0.1.1"
authors = ["Paul Masurel <paul.masurel@gmail.com>"]
build = "build.rs"
license = "MIT"

description = """Tantivy is a search engine library."""

documentation = "http://fulmicoton.com/tantivy/tantivy/index.html"
homepage = "https://github.com/fulmicoton/tantivy"
repository = "https://github.com/fulmicoton/tantivy"

readme = "README.md"
keywords = ["search", "information", "retrieval"]

[dependencies]
byteorder = "0.4"
memmap = "0.2"
lazy_static = "0.1.15"
regex = "0.1"
fst = "0.1.34"
atomicwrites = "0.0.14"
tempfile = "2.0.0"
rustc-serialize = "0.3.16"
log = "0.3.5"
combine = "1.3.0"
tempdir = "0.3.4"
bincode = "0.4.0"
libc = "0.2.6"
num_cpus = "0.2"
itertools = "0.4.16"
lz4 = "1.13.131"
time = "0.1.34"
uuid = "0.1"
chan = "0.1.18"

[dev-dependencies]
rand = "0.3.13"

[build-dependencies]
gcc = "0.3.24"

# [profile.release]
# debug = true


