[package]
name = "tantivy"
version = "0.1.0"
authors = ["Paul Masurel <paul.masurel@gmail.com>"]
build = "build.rs"
license = "MIT"

description = """Tantivy is a search engine library."""

documentation = "http://fulmicoton.com/tantivy/tantivy/index.html"
homepage = "https://github.com/fulmicoton/tantivy"
repository = "https://github.com/fulmicoton/tantivy"

readme = "README.md"
keywords = ["search", "information", "retrieval"]

[dependencies]
byteorder = "0.4"
memmap = "0.2"
lazy_static = "0.1.15"
regex = "0.1"
fst = "0.1.31"
atomicwrites = "0.0.14"
tempfile = "2.0.0"
rustc-serialize = "0.3.16"
log = "0.3.5"
combine = "1.3.0"
tempdir = "0.3.4"
bincode = "0.4.0"
libc = "0.2.6"
num_cpus = "0.2"
itertools = "0.4.16"
lz4 = "1.13.131"
time = "0.1.34"
uuid = "0.1"
iron = "0.4"
staticfile = "0.3.0"
persistent="0.2.0"
ansi_term = "0.8.0"
clap = "2"
mount = "0.2.1"

[dev-dependencies]
rand = "0.3.13"

[build-dependencies]
gcc = "0.3.24"

[[bin]]
name = "tantivy-cli"
path = "src/cli/main.rs"
doc = false

# [profile.release]
# debug = true

[dependencies.urlencoded]
version = "0.4"


