[package]
name = "tantivy"
version = "0.1.0"
authors = ["Paul Masurel <paul.masurel@gmail.com>"]
build = "build.rs"

[dependencies]
byteorder = "0.4"
memmap = "0.2"
lazy_static = "0.1.*"
regex = "0.1"
fst = "0.1.31"
atomicwrites = "0.0.14"
tempfile = "2.0.0"
rustc-serialize = "0.3.16"
log = "0.3.5"
combine = "*"
tempdir = "0.3.4"
bincode = "0.4.0"
libc = "0.2.6"
argparse = "*"
num_cpus = "0.2"
itertools = "0.4.16"
lz4 = "1.13.131"
time = "0.1.34"
uuid = "0.1"

[dev-dependencies]
rand = "0.3.13"

[build-dependencies]
gcc = "0.3.24"

[[bin]]
name = "tantivy_merge"
path = "src/cli/merge.rs"

[[bin]]
name = "tantivy_bench"
path = "src/cli/bench.rs"

[profile.release]
debug = true