[package]
name = "tantivy"
version = "0.1.0"
authors = ["Paul Masurel <paul.masurel@gmail.com>"]

[dependencies]
byteorder = "0.4.2"
itertools = "0.4.5"
memmap = "0.2.3"
lazy_static = "0.1.*"
regex = "0.1"
fst = "0.1.26"
rand = "0.3.13"
atomicwrites = "0.0.14"
tempfile = "2.0.0"
